# Generated by Django 2.1.4 on 2019-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('department', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=3)),
                ('fa', models.ManyToManyField(to='projects.FA')),
            ],
        ),
    ]
